"""
This Django migration class was generated by Django 5.0 on 2023-12-30 18:14.
It represents a database migration that creates a 'Product' model with specific fields.
"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Attributes:
    - initial: A boolean indicating if this is the initial migration.
    - dependencies: A list of dependencies, indicating other migrations that must be applied
    before this one.
    - operations: A list of migration operations, including the creation of the 'Product' model.

    The 'Product' model has the following fields:
    - id: Auto-generated BigAutoField serving as the primary key.
    - name: CharField with a maximum length of 50 characters.
    - description: TextField allowing for optional and longer product descriptions.
    - price: DecimalField representing the product price with 2 decimal places and a maximum of
    10 digits.
    - created_at: DateTimeField set to auto_now_add, capturing the creation timestamp.
    - updated_at: DateTimeField set to auto_now, capturing the last update timestamp.
    """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
