version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Use Pipenv to install dependencies
python:
  version: "3.11"
  install:
    - method: pip
      path: .
      extra_requirements:
        - -r Pipfile