name: Django Management System Documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11.5']
        pipenv-version: ['2023.11.15']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: pip install pipenv==${{ matrix.pipenv-version }}
      - name: Install dependencies
        run: pipenv install --dev
      - name: Install sphinx dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser django django-rest-framework django-cors-headers
      - name: Sphinx build
        run: |
          sphinx-build docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
