name: Push
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        pipenv-version: [' 2023.11.15']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: pip install pipenv==${{ matrix.pipenv-version }}
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run tests
        run: pipenv run pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        pipenv-version: ['2021.5']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pipenv
        run: pip install pipenv==${{ matrix.pipenv-version }}
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run black
        run: pipenv run black . --check
      - name: Run isort
        run: pipenv run isort . --check-only --profile black
      - name: Run flake8
        run: pipenv run flake8 .
      - name: Run bandit
        run: pipenv run bandit .
      - name: Run safety
        run: pipenv run safety check
